// Regenerate web/public/objects/*.svg (clip-art for the add_object action) from shared/objects.json.
// The SVGs are committed, so the app works offline; run this only after editing the catalog:
//   npm run objects --workspace web
// Source: Microsoft Fluent Emoji (Flat), MIT, via the pinned Iconify JSON package below. Uses `npm pack`
// so npm's own registry/proxy settings apply.
import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";

const PACKAGE = "@iconify-json/fluent-emoji-flat@1.2.6";
const SIZE = 256; // intrinsic px size; the art is vector, this only sets the default raster size

const here = dirname(fileURLToPath(import.meta.url));
const catalog = JSON.parse(readFileSync(join(here, "../../shared/objects.json"), "utf8"));
const outDir = join(here, "../public/objects");

/** Read one file out of a .tgz (ustar) without a tar dependency. */
function readFromTgz(tgz, wanted) {
  const tar = gunzipSync(tgz);
  for (let off = 0; off + 512 <= tar.length; ) {
    const name = tar.toString("utf8", off, off + 100).replace(/\0.*$/s, "");
    if (!name) break;
    const size = parseInt(tar.toString("utf8", off + 124, off + 136).replace(/\0.*$/s, "").trim() || "0", 8);
    if (name === wanted) return tar.subarray(off + 512, off + 512 + size);
    off += 512 + Math.ceil(size / 512) * 512;
  }
  throw new Error(`${wanted} not found in package`);
}

const tmp = mkdtempSync(join(tmpdir(), "objects-"));
try {
  const file = execFileSync("npm", ["pack", PACKAGE, "--silent", "--pack-destination", tmp], {
    encoding: "utf8",
    shell: process.platform === "win32",
  }).trim();
  const set = JSON.parse(readFromTgz(readFileSync(join(tmp, file.split("\n").at(-1))), "package/icons.json").toString("utf8"));

  mkdirSync(outDir, { recursive: true });
  for (const f of readdirSync(outDir)) if (f.endsWith(".svg")) rmSync(join(outDir, f));
  const missing = [];
  for (const [name, { icon }] of Object.entries(catalog)) {
    const data = set.icons[icon] ?? set.icons[set.aliases?.[icon]?.parent];
    if (!data) {
      missing.push(`${name} (${icon})`);
      continue;
    }
    const w = data.width ?? set.width;
    const h = data.height ?? set.height;
    const svg =
      `<svg xmlns="http://www.w3.org/2000/svg" width="${SIZE}" height="${Math.round((SIZE * h) / w)}" ` +
      `viewBox="${data.left ?? 0} ${data.top ?? 0} ${w} ${h}">${data.body}</svg>\n`;
    writeFileSync(join(outDir, `${name.replace(/ /g, "-")}.svg`), svg);
  }
  writeFileSync(
    join(outDir, "LICENSE.md"),
    `# Object clip-art\n\nGenerated by \`web/scripts/fetch-objects.mjs\` from Fluent Emoji Flat (${PACKAGE}).\n\n` +
      `Copyright (c) Microsoft Corporation. MIT License: https://github.com/microsoft/fluentui-emoji/blob/main/LICENSE\n`,
  );
  if (missing.length) throw new Error(`icons not in ${PACKAGE}: ${missing.join(", ")}`);
  console.log(`wrote ${Object.keys(catalog).length} objects -> ${outDir}`);
} finally {
  rmSync(tmp, { recursive: true, force: true });
}
